version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - alta_network

  # Strapi service (commented out for future use)
  # strapi:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.strapi
  #   ports:
  #     - "1337:1337"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_CLIENT=sqlite
  #   volumes:
  #     - strapi_data:/app/database
  #     - strapi_uploads:/app/public/uploads
  #   restart: unless-stopped
  #   networks:
  #     - alta_network

networks:
  alta_network:
    driver: bridge

# Volumes for Strapi (commented out for future use)
# volumes:
#   strapi_data:
#   strapi_uploads: 