version: '3.8'

services:
  tsc-web:
    build: .
    container_name: tsc-web
    ports:
      - "8888:8888"
      - "5050:5050"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tsc_network

networks:
  tsc_network:
    driver: bridge