version: '2.2'

services:
  tsc_web:
    build: .
    container_name: tsc_web
    ports:
      - "8081:80"
      - "8443:443"
      - "5050:5050"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
#      start_period: 40s

#    volumes:
#      - /var/www/html/altaqa:/app

